apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    project: multi-cloud-k8s
    environment: dev
    managed-by: manifests
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://mc-kps-gke-prometheus.monitoring.svc.cluster.local:9090
        editable: false
        isDefault: false
        jsonData:
          httpMethod: POST
      - name: Thanos
        uid: thanos
        type: prometheus
        access: proxy
        url: http://thanos-query.monitoring.svc.cluster.local:9090
        editable: false
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          manageAlerts: true
