apiVersion: 1
deleteDatasources:
  - name: Prometheus GKE
    orgId: 1
  - name: Thanos Aggregated
    orgId: 1
prune: true
datasources:
  - name: Prometheus GKE
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      timeInterval: 30s
      manageAlerts: false
  - name: Thanos Aggregated
    uid: thanos
    type: prometheus
    access: proxy
    url: ${THANOS_URL}
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      timeInterval: 30s
      manageAlerts: false
