fullnameOverride: mc-grafana

commonLabels:
  project: multi-cloud-k8s
  environment: dev
  managed-by: helm

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: monitoring
    folderAnnotation: grafana_folder
    provider:
      allowUiUpdates: false
      disableDelete: false
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"
    searchNamespace: monitoring

grafana.ini:
  server:
    root_url: http://localhost:3000
  users:
    default_theme: dark
  auth:
    disable_login_form: false
  feature_toggles:
    enable: publicDashboards
