apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-istio-sources
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: multi-cloud-k8s
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
      - virtualservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
      - httproutes
      - grpcroutes
      - tlsroutes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-istio-sources
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: multi-cloud-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-istio-sources
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns