global:
  nodeAffinity:
    key: cloud.google.com/gke-nodepool
    values:
      - primary

api-gateway:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: mc-k8s-api-gw@mc-k8s-platform-dev.iam.gserviceaccount.com

order-service:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: mc-k8s-order@mc-k8s-platform-dev.iam.gserviceaccount.com

inventory-service:
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: mc-k8s-inventory@mc-k8s-platform-dev.iam.gserviceaccount.com
